# Generated by Django 2.0.2 on 2018-03-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180306_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
