# Generated by Django 2.0.2 on 2018-03-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180306_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fare',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
