# Generated by Django 2.0.2 on 2018-03-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fare',
        ),
    ]
