# Generated by Django 2.0.2 on 2018-03-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_ticket_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
