# Generated by Django 2.0.2 on 2018-03-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20180313_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
