# Generated by Django 2.0.2 on 2018-03-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='settings.MEDIA_ROOT/default_event.jpg', upload_to=''),
        ),
    ]
